### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by charchit** [ratchek/colornote_to_joplin#2]
I have been trying to use this python file to copy from colornote to joplin. I also keep getting this error. I followed all the steps but could not figure out what was wrong.

![Capture](https://user-images.githubusercontent.com/6505015/210295699-e19fe62c-2cb5-4a46-9a79-be227672b9f8.PNG)

**Comment by jpduyx** [comment]
similar issue here: 

```
Great! What port is the webclipper listening on?  
41184
Awesome! I'll get right to it. Please hold...
Traceback (most recent call last):
  File "/home/jpduyx/Project/colornote_to_joplin/colornote_to_joplin.py", line 106, in <module>
    categories = get_categories(database)
  File "/home/jpduyx/Project/colornote_to_joplin/colornote_to_joplin.py", line 84, in get_categories
    record = json.loads( db_results[0][0] )['D']
IndexError: list index out of range

```

**Comment by jpduyx** [comment]
my results when i run the select statement found in the get_categories function

```
SELECT note FROM notes WHERE title = "name_label_0";

Execution finished without errors.
Result: 0 rows returned in 4ms
```

I guess the script expects to be more than 0 categories available and wasn't prepared that some people use colornote without categories?

**Comment by jpduyx** [comment]
``
select DISTINCT color_index from notes;
3
``
Only color_index with value 3 in my database ... trying to hack a way to make the script work 

change line 105 to 107 in the script to: 
```python
joplin.create_top_level_folder()  
#categories = get_categories(database)
categories = {"3": "colornotes"}
```

gives me the following result:

```
Great! What port is the webclipper listening on?  
41184
Awesome! I'll get right to it. Please hold...
--- Creating notes in colornotes---
Done!
Looks like we're all done! Thanks.
```

And the notes appear in Joplin :-) 


I didn't use the color / categories and the script expects something what wasn't there in my colornotes database. 

So if you find you have the same "issue" with this script ... perhaps my steps can help you find a work around based on your situation

**Comment by ratchek** [comment]
Thanks for debugging that and documenting how you solved it! I don't have colornote anymore, but if I change that in the code, would you be willing to test if it works for you? (Or you can just submit a pull request)

**Comment by jpduyx** [comment]
@ratchek,

Getting my data out of colornotes is just one of the many steps to migrate to a new phone. No plan on using colornotes any longer.

I'm  actually not very sure how to test the code for different use cases of colornotes... and im quite sure the error occurred in these cases because I used colornote a bit different than you might have used it. I never actually used colors or labels or so for the notes for example and I believed that the original code searches for something like that. 

What I did was just a dirty hack to make it work on my database, not a real fix
Don't use colornotes anymore but do have the copy of the database somewhere.
If you can update the code I can surely help test it a copy of my database.

**Comment by zeocs** [comment]
Hi, I had this issue too. It happens if not even a single category is named. In this case, the SQL statement returns zero records, causing the error. I implemented a clean fix for this. I'll make a pull request :)
